printer_names:
  Canon Pixma PRO-100:
  - PRO-100
  - Pro-100
  - pro-100
  - pixmapro100
  - pro100
  - CanPro-100
  - CanPro100
  - canpro-100
  - canpro100
  - CANPRO-100
  - CANPRO100
  Canon iPF6450:
  - Can6450
  - iPF6450
  - ipf6450
  - iPf6450
  - ipf6400
  Canon iPF8400:
  - Can8400
  Epson P700:
  - P700
  - SC-P700
  - EpsSC-P700
  Epson P900:
  - P900
  - SC-P900
  - EpsSC-P900
  - p900
  Epson P7500:
  - P7500
  - SC-P7500
  - p7500
  Epson P7570:
  - P7570
  - SC-P7570
  - p7570
  - EpsSC-P7570
  - Epson SureColor P7570
  - Epson SureColor SC-P7570
  Epson P9500:
  - EpsSC-P9500
  Epson P9570:
  - P9570
  - SC-P9570
brand_name_mappings:
  Canson:
  - cifa
  - CIFA
  - canson
  - Canson
  Hahnemuehle:
  - HFA
  - hfa
  - Hahnemuehle
  - hahnemuehle
  MOAB:
  - MOAB
  - Moab
  - moab
paper_brands:
- Hahnemuehle
- Canson
- MOAB
- Moab
printer_remappings:
  Canon iPF8400: Canon iPF6450
  Epson P700: Epson P900
  Epson P7500: Epson P7570
  Epson P9500: Epson P7570
  Epson SureColor P7570: Epson P7570
